### PR TITLE
Move latest published templates to master

### PR DESCRIPTION
**Pull request by joebochill**
All of the React templates have now been published as 'latest' versions at 1.0.0

#### Changes proposed in this Pull Request:
- Add templates for routing and authentication

### CODE REVIEW

**Comment by jeffvg** [comment]
Just need to update the blank template to include typescript. Routing and Auth is good

**Comment by joebochill** [comment]
> Just need to update the blank template to include typescript. Routing and Auth is good

I just ran through all of the templates again and couldn't reproduce the typescript issue (though I definitely saw it this morning once). It might be some sort of yarn cache thing 🤷 

All three TS templates as published today have typescript 4.2+ included in their template.json files.

**Comment by huayunh** [comment]
What was the idea behind [adding highcharts to package.json](https://github.com/pxblue/react-cli-templates/blob/e3a165c59edf3a85183926af174d390e77a440ad/authentication-typescript/template.json#L15)?

**Comment by huayunh** [comment]
Why was typescript [under `dependencies` instead of `devDependencies`](https://github.com/pxblue/react-cli-templates/blob/e3a165c59edf3a85183926af174d390e77a440ad/authentication-typescript/template.json#L21)?

**Comment by huayunh** [comment]
Was it intentional to include typescript as a dependency [in a js template](https://github.com/pxblue/react-cli-templates/blob/dev/authentication/template.json#L21)?

**Comment by joebochill** [comment]
> What was the idea behind [adding highcharts to package.json](https://github.com/pxblue/react-cli-templates/blob/e3a165c59edf3a85183926af174d390e77a440ad/authentication-typescript/template.json#L15)?

It is a peerDependency of the auth workflow: https://github.com/pxblue/react-workflows/blob/dev/login-workflow/package.json#L33

This is a holdover from when we innersourced this from Shiverware. It does not appear to be used internal to the workflow itself, but we export a utility function to simplify internationalization of chart labels. It could _probably_ be removed if we want to.

**Comment by joebochill** [comment]
> Was it intentional to include typescript as a dependency [in a js template](https://github.com/pxblue/react-cli-templates/blob/dev/authentication/template.json#L21)?

Not intentional...removed.

**Review by huayunh — APPROVED** [review]
[This guy](https://github.com/pxblue/react-cli-templates/blob/d31e4c841fca42deab9d78cb830f2bf8d34ed18a/routing/template.json#L17) too?

Looking good otherwise.

**Comment by huayunh** [comment]
> ...export a utility function to simplify internationalization of chart label

Sounds like something for `@pxblue/highcharts`

**Comment by huayunh** [comment]
https://github.com/pxblue/react-cli-templates/blob/dev/blank/template.json#L10-L12 dev?

**Comment by joebochill** [comment]
> https://github.com/pxblue/react-cli-templates/blob/dev/blank/template.json#L10-L12 those shall be in dev?

These templates were all based off of the official create-react-templates for javascript and typescript, which have them listed in normal dependencies (https://github.com/facebook/create-react-app/blob/master/packages/cra-template/template.json#L4), but it doesn't hurt to move them to dev...everything gets installed in the same place.

**Comment by joebochill** [comment]
> > ...export a utility function to simplify internationalization of chart label
> 
> Sounds like something for `@pxblue/highcharts`

Maybe. We'd have to investigate it a little. Right now it's tied into the i18n library. Our current highcharts package does not have any dependence on i18n (and I don't necessarily think we would want to introduce it). I'd be more inclined to just remove the function and the highcharts dependency altogether, and leave that up to the end users to sort out, since we don't use any charts internally.

**Comment by joebochill** [comment]
I published updated packages for the JS templates that had TS dependency.

**Review by emclaug2 — APPROVED** [review]

**Pull request merged**
