### PR TITLE
Add JS templates for Authentication and Routing

### PR DESCRIPTION
**Pull request by joebochill**
For PXBLUE-XXXX .

#### Changes proposed in this Pull Request:
- Add Js versions of the Authentication and Routing templates
- Clean up the template readmes
- Update the default tests so that they pass in all of the templates

### CODE REVIEW

**Review by jeffvg — APPROVED** [review]

**Comment by huayunh** [comment]
Add screenshots or diagrams to the readmes to explain what each template does (or add them in the CLI package's readme).

Update docit to reflect the change.

Cool with me if you make a separate issue on this for the next sprint — I suppose this is out-of-scope for this one.

**Comment by joebochill** [comment]
> Add screenshots or diagrams to the readmes to explain what each template does (or add them in the CLI package's readme).

What kind of screenshots would you be looking for here? The blank template doesn't really do anything, the routing one just adds a drawer (I can add a link to the drawer storybook), and the login one is well-documented in the @pxblue/react-auth-workflow package (with images). I did a quick search and of the top 20 CRA templates on NPM, only one of them has an image.

> Update docit to reflect the change.
> 
> Cool with me if you make a separate issue on this for the next sprint — I suppose this is out-of-scope for this one.

I will make a story for this. We can probably wait on updating the doc-it page until we have templates for all of the frameworks so we don't have to put in conditional explanations and then update them each time we do new ones. The Readme on GitHub will stay up to date with the latest templates available and we link out to that from doc-it, so we should be safe for a while. We may also want to _keep_ doc-it pretty simple with links out so we don't duplicate documentation on github and doc-it.

**Comment by huayunh** [comment]
I agree on the docit staying no more than it needs to be. I am just saying this bc I feel the need to "announce" the template thing on docit.

I would say add some screenshots to at least the root readme, so that an external user may decide which template to pick at a glance. Or at the minimum, add a brief text description for easier side-by-side comparison.

**Comment by joebochill** [comment]
@huayunh Brian was also asking about a way to show the templates. I'll update the root readme to be more descriptive.

**Comment by huayunh** [comment]
#ManagerPressure

**Comment by huayunh** [comment]
| | a blank landing page | drawer and routing and several placeholder pages  | authentication workflow  |
| - | - | - | - |
| template=blank | ✔️  | ✔️  | ✔️  |
| template=routing | | ✔️  | ✔️  |
| template=auth | | | ✔️  |

**Comment by huayunh** [comment]
And perhaps captions for each screenshot?

**Pull request merged**
