### PR TITLE
Go BLUI

### PR DESCRIPTION
**Pull request by emclaug2**
#### Changes proposed in this Pull Request:
- Publish BLUI React Templates

### CODE REVIEW

**Comment by emclaug2** [comment]
Changelogs need updated for this PR.

**Comment by ektasawant** [comment]
Hi @emclaug2 , raised PR  for [37](https://github.com/pxblue/react-cli-templates/pull/37)  updating `changelog` and `package.json`. Could you please review it?

**Comment by jeffvg** [comment]
not sure what the plan for this repo is later in the sprint but we have px blue in home/app files

image

**Comment by andrupu** [comment]
I see it in the template/src/App.tsx file (lines 74-75) for both blank-typescript and blank templates.  I think we can change that PX Blue reference.  I can update this by end of day Tuesday, December 7th.  Just thumbs up this and I will get to it.  Otherwise I will leave this open to discussion.

**Comment by ektasawant** [comment]
> I see it in the template/src/App.tsx file (lines 74-75) for both blank-typescript and blank templates. I think we can change that PX Blue reference. I can update this by end of day Tuesday, December 7th. Just thumbs up this and I will get to it. Otherwise I will leave this open to discussion.

Hi @andrupu , will raise PR to fix this, thanks for looking into it :).

**Comment by ektasawant** [comment]
> not sure what the plan for this repo is later in the sprint but we have px blue in home/app files
> 
> image

Raised PR for fixing pxb ref https://github.com/pxblue/react-cli-templates/pull/38. @andrupu , @emclaug2 and @jeffvg please review. For changing logo image may be we can fix it once we finalised logo image.

**Review by jeffvg — APPROVED** [review]
looks good

**Review by andrupu — APPROVED** [review]

**Comment by ektasawant** [comment]
Hi @emclaug2 , updated changelog file with today's date. Please review https://github.com/pxblue/react-cli-templates/pull/39 ?

**Review by joebochill — APPROVED** [review]
Looks good..Assuming we tested these locally with the CLI to make sure they actually work right?

**Review by huayunh — APPROVED** [review]

**Comment by jeffvg** [comment]
> Looks good..Assuming we tested these locally with the CLI to make sure they actually work right?

sure did

**Pull request merged**
